// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaUbuY5-YmVCQ77Kx6zXwiYXOm4OXevpo',
    appId: '1:227702736019:web:8e7515c521d80e283fb966',
    messagingSenderId: '227702736019',
    projectId: 'item-database-3588c',
    authDomain: 'item-database-3588c.firebaseapp.com',
    storageBucket: 'item-database-3588c.firebasestorage.app',
    measurementId: 'G-XX57V7WW1K',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaUbuY5-YmVCQ77Kx6zXwiYXOm4OXevpo',
    appId: '1:227702736019:web:931311a5c4628bcc3fb966',
    messagingSenderId: '227702736019',
    projectId: 'item-database-3588c',
    authDomain: 'item-database-3588c.firebaseapp.com',
    storageBucket: 'item-database-3588c.firebasestorage.app',
    measurementId: 'G-QZKGXEPG1J',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9lZU5BG351DS-4vKf6BSjbLMRyHM6n08',
    appId: '1:227702736019:ios:21385fd2798bd9cd3fb966',
    messagingSenderId: '227702736019',
    projectId: 'item-database-3588c',
    storageBucket: 'item-database-3588c.firebasestorage.app',
    iosBundleId: 'com.example.marketplace',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9lZU5BG351DS-4vKf6BSjbLMRyHM6n08',
    appId: '1:227702736019:ios:21385fd2798bd9cd3fb966',
    messagingSenderId: '227702736019',
    projectId: 'item-database-3588c',
    storageBucket: 'item-database-3588c.firebasestorage.app',
    iosBundleId: 'com.example.marketplace',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC72BuOsKpFgdhAyAL1JRJUjmxRD6hQ6os',
    appId: '1:227702736019:android:d113b76fa4f5d5b23fb966',
    messagingSenderId: '227702736019',
    projectId: 'item-database-3588c',
    storageBucket: 'item-database-3588c.firebasestorage.app',
  );

}